# Generated by Django 5.2.1 on 2025-05-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numOne", models.FloatField()),
                ("numTwo", models.FloatField()),
                ("numThree", models.FloatField()),
                ("media", models.FloatField(blank=True, null=True)),
                ("median", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(default="Process", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
