services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./desafio_dos_numeros_backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    command: celery -A desafio_dos_numeros_backend worker -l info
    volumes:
      - ./desafio_dos_numeros_backend:/app
    depends_on:
      - backend
      - rabbitmq
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: desafio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"